### ISSUE TITLE
backend test script?

### ISSUE THREAD

**Issue by jsms90** [FAC10/week4-SoFLY#77]
This is entirely missing

**Comment by yvonne-liu** [comment]
All of our backend tests are in `backendtests.js` using `tape` 😊 

See our `tests.js` file: 
```
var test = require('tape');
var backendTests = require('./backendtests.js');
```

**Comment by jsms90** [comment]
@yvonne-liu I meant that you have no "script" i.e. `npm test` in your `package.json` doesn't run your backend tests

**Comment by jsms90** [comment]
Ahhh woops!! :relaxed: :+1:
